### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Misco** [alessandrio/syncing-brackets#1]
Hello,

i´m sorry but i don´t understand it. Where to put the php file und what filename?
i tried index.php in root of my subdomain, its not working.
i use bracket

Thanks for advise.

**Comment by Misco** [comment]
syncing failed! is the error. Try with an .txt

**Comment by Misco** [comment]
ok, needed serverroot path. thanks for this extension

**Comment by alessandrio** [comment]
Exactly, that's what you missed, make sure you put the phyton or php code and give it the necessary permissions and then put the url where your file is on your server in the extension nut configuration and that would work perfectly
