### ISSUE TITLE
When installing the update to Brackets, your extension fails

### ISSUE THREAD

**Issue by Whirl3d** [alessandrio/syncing-brackets#2]
Your Brackets extension forces the user to go through a bunch of steps that require editing a text file, uploading to a server, copying the URL and pasting it into your extension JUST TO USE BRACKETS. If I don't want to do that for whatever reason, you make brackets lock up and there is nothing I can do to continue. I am going to have to dig into the settings in another text editor since you bricked this one to figure out where your extension is loaded to disable it. 

Since I am reviewing Brackets, your extension and its brick behavior is going to give brackets (and your extension) a terrible review. I can't even use the software. So frustrating.

Please revise this extension with a non-modal announcement that encourages NOT REQUIRES the user to configure your extension. At least you could allow a CANCEL or SKIP button. 
Thanks.

**Comment by alessandrio** [comment]
Thanks for your support, I hadn't noticed it, you are absolutely right, in the next update I will solve that and more details.
