### ISSUE TITLE
syncing failed!

### ISSUE THREAD

**Issue by johvdrie** [alessandrio/syncing-brackets#3]
Hi alessandrio,

I installed your extension syncing-cloud for Brackets but it didn't work.
I created the prerequisites index.php and index.py and placed both files in the folder 'syncing'
The copied the url in the syncing initial setting: https://beneluxepr.ugent.be/syncing/
When I press the cloud button, I see the syncing box where the first field is the local filename
C:/Program Files (x86)/Brackets/BeneluxEPR/index.html
and the second field the upload path \\files.ugent.be
but it doesn't work ...

Thank you for helping me out!

Best regards, Johan

**Comment by alessandrio** [comment]
Hello,
it looks like your server file does not have permissions to work as it should.
make sure you modify its access:
https://serverfault.com/questions/62893/you-don-t-have-permission-to-access-index-py-on-this-server

**Comment by johvdrie** [comment]
Hello,
indeed permissions are now for both set to 755.
This is the .htaccess content
# by default directoy listing should be off
Options -Indexes
RewriteEngine On
Options +ExecCGI
AddHandler cgi-script .py
DirectoryIndex index.py
# end of .htaccess

It just flashes for a moment green, but turns red with syncing failed!
The second field in the Brackets syncing box (I guess this the upload path) is \\\files.ugent.be\WWW but it always places a '/' at the end. Could this be the fault ?

**Comment by alessandrio** [comment]
It may be that your server does not accept the use of python or maybe it does not allow you to exit the 'cgi-bin' folder. in any case try just typing a "Hello World" and testing:

~file index.py~

    #!/usr/bin/env python
    print "Content-Type: text/html"

**Comment by johvdrie** [comment]
Should I replace the "DirectoryIndex index.py" with "#!/usr/bin/env python
print "Content-Type: text/html"" ?

**Comment by johvdrie** [comment]
When I visit the website, it just prints the full content of index.py
If I use php, I get 403 Forbidden, You don't have permission to access this resource.

**Comment by alessandrio** [comment]
that's fine.

     DirectoryIndex index.html index.php index.py

----
now create an index.py file and run it to see if it prints the text.

    #!/usr/bin/env python
    print "Content-Type: text/html"
    print "Hello World"
otherwise your server is not working.

**Comment by JialuZhang** [comment]
@johvdrie 

In your posted configuration,
```
RewriteEngine On
```

the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by johvdrie** [comment]
Thank you Jialu Zhang!

________________________________
Van: Jialu Zhang ***@***.***>
Verstuurd: donderdag 18 maart 2021 01:07
Aan: alessandrio/syncing-cloud
Cc: johvdrie; Mention
Onderwerp: Re: [alessandrio/syncing-cloud] syncing failed! (#3)


@johvdrie<https://github.com/johvdrie>

In your posted configuration,

RewriteEngine On



the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:

run_rewritemap_programs(server_rec *s , apr_pool_t *p){

if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"

  return APR_SUCCESS; // early return

rewritemap_program(...); // usage of "RewriteRule"

}
